#!/usr/bin/env python3
"""Slint image URLs are literals: build a bounded atlas lookup, no runtime paths."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
frames = sorted(p for p in (ROOT / 'assets/sprites').glob('*.png')
                if p.stem.endswith(('_a', '_b')) and '_climb_' not in p.stem)
text = '''// Generated by tools/generate-sprites.py; original artwork: see SOURCES.md.
export component PetSprite inherits Image {
    in property <string> form: "egg";
    in property <string> animation: "idle";
    in property <bool> frame: false;
    in property <color> tint;
    property <string> key: form + "_" + animation + (frame ? "_b" : "_a");
    image-rendering: pixelated;
    image-fit: contain;
    colorize: tint;
    source:
'''
for frame in frames:
    text += f'        key == "{frame.stem}" ? @image-url("assets/sprites/{frame.name}") :\n'
text += '        @image-url("assets/sprites/egg_idle_a.png");\n}\n'
(ROOT / 'sprites.slint').write_text(text)
